[package]
name = "payload"
version = "0.1.0"
edition = "2021"

[dependencies]
flexi_logger = "0.27.4"
log = "0.4.20"
toml = "0.8.19"
anyhow = "1.0.79"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
getset = "0.1.2"